### ISSUE TITLE
Update tzdata package in cluster-proportional-autoscaler image

### ISSUE THREAD

**Issue by jonesbr17** [kubernetes-sigs/cluster-proportional-autoscaler#100]
[DLA-2424-1](https://www.tenable.com/plugins/nessus/142169) is a vulnerability impacting the cluster-proportional-autoscaler image. The tzdata package will need to be upgraded to resolve.

**Comment by MrHohn** [comment]
@jonesbr17 Thanks for reporting. I'm not sure about which versions are impacted as I don't find any import of the tzdata package. Also CPA doesn't use debian as the base image IFAICT. Could you give more context? Thanks.

**Comment by jonesbr17** [comment]
I'm seeing the issue on 1.8.3 as well as 1.7.1. From what I've seen, images built on distroless just need to be rebuilt to pick up the remedy.

**Comment by MrHohn** [comment]
Acked, I will add new release with the latest image from distroless.

**Comment by jonesbr17** [comment]
Update, the change to fix the vulnerability has been merged: https://github.com/kubernetes/kubernetes/pull/98401
I do not see new images published yet however, will keep an eye out for that.

**Comment by jonesbr17** [comment]
There is a new release of `gcr.io/distroless/static:nonroot` available, so publishing a new release at this point should resolve the vulnerabilities

**Comment by rtheis** [comment]
@jonesbr17 has this problem been resolved?

**Comment by jonesbr17** [comment]
Yes this was resolved in release 1.8.4 and can be closed out.
