### ISSUE TITLE
JSON broken in README.md

### ISSUE THREAD

**Issue by MRostanski** [kubernetes-sigs/cluster-proportional-autoscaler#102]
Hi,
I have to report that there is an error in JSON provided as an example of linear object in default configuration.
The comma and quotes are necessary for proper config.

Is now:

`data:
  linear: |-
    {
      "coresPerReplica": 2,
      "nodesPerReplica": 1,
      "min": 1,
      "max": 100,
      "preventSinglePointFailure": true
      "includeUnschedulableNodes": true
    }`

Should be:

`data:
  linear: |-
    {
      "coresPerReplica": 2,
      "nodesPerReplica": 1,
      "min": 1,
      "max": 100,
      "preventSinglePointFailure": "true",
      "includeUnschedulableNodes": "true"
    }`

Sorry, I have created (probably wrong) PR with those changes in https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/pull/101

**Comment by MrHohn** [comment]
Fixed by https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/pull/107.
