### ISSUE TITLE
Feature Request: Helm chart for cluster-proportional-autoscaler

### ISSUE THREAD

**Issue by SatoruItaya** [kubernetes-sigs/cluster-proportional-autoscaler#103]
I would like the Helm Chart to deploy the cluster-proportional-autoscaler.

**Comment by MrHohn** [comment]
@SatoruItaya Thanks for the request. TBH I'm not familiar with with Helm chart integration, so any pointer for that would be very helpful!

**Comment by krmichel** [comment]
/reopen
@MrHohn If the project is open to it I could make a PR to add a helm chart.  Just let me know

**Comment by MrHohn** [comment]
@krmichel Thanks for the offering - yep a PR would be awesome.
