### ISSUE TITLE
What does "cores" mean？

### ISSUE THREAD

**Issue by fengmingxing** [kubernetes-sigs/cluster-proportional-autoscaler#106]
What does "cores" mean？That means the cluster's total cpu core or core business ？
replicas = max( ceil( cores * 1/coresPerReplica ) , ceil( nodes * 1/nodesPerReplica ) )
replicas = min(replicas, max)
replicas = max(replicas, min)

**Comment by MrHohn** [comment]
@fengmingxing Yep, cores = cpu cores in this context.

**Comment by fengmingxing** [comment]
> @fengmingxing Yep, cores = cpu cores in this context.

ok,Thank you.

**Comment by MrHohn** [comment]
Closing this for now but feel free to reopen if you have more questions.
