### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by bgray-onica** [kubernetes-sigs/cluster-proportional-autoscaler#108]
Hello,

I am working on moving a customer to newer versions, but it seems there's not been much activity. Is this just a natural end to very active development or has this project been superseded by something else?

Thanks!

**Comment by MrHohn** [comment]
@bgray-onica Thanks for the question. This project has not been superseded by something else - it is still being used in production workload and is maintained actively - just that not many features are being added.

**Comment by bgray-onica** [comment]
That was what I figured, but wanted to be sure. Thank you!
