### ISSUE TITLE
Minimum replicas in laddermode is not zero

### ISSUE THREAD

**Issue by grieshaber** [kubernetes-sigs/cluster-proportional-autoscaler#110]
In the Readme it says, that it is possible to set the replicas to zero when using laddermode. Additionally, it states, that one of `coresToReplicas` or `nodesToReplicas` can be omitted.

But, scaling to zero is not possible when one of the above is omitted. This is because the default number of replicas is 1, if the corresponding list of entries is empty 
https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/blob/fe440432e1144a1193c421544fd9c8cd9731a4bc/pkg/autoscaler/controller/laddercontroller/ladder_controller.go#L133

If the calculated number of replicas from the given config is 0, the comparison https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/blob/fe440432e1144a1193c421544fd9c8cd9731a4bc/pkg/autoscaler/controller/laddercontroller/ladder_controller.go#L126
does return the default value of 1.

**Comment by grieshaber** [comment]
@MrHohn unfortunately, i did not link the PR to this issue. This should be resolved and we'd appreciate, if a new release could be created with the fix included. Anything we can do?

**Comment by MrHohn** [comment]
Oops, I thought we released a new version that includes this and I am wrong.

https://github.com/kubernetes/k8s.io/pull/2532 is promoting the new images.

**Comment by MrHohn** [comment]
Release 1.8.5 is out: https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/1.8.5
