### ISSUE TITLE
Support ignoring NotReady/Tainted nodes

### ISSUE THREAD

**Issue by tbalzer** [kubernetes-sigs/cluster-proportional-autoscaler#115]
In our cloud environment rapid node autoscaling is realized by shutting down nodes without removing them from the cluster. This means in a cluster that has a high scaling range at times most of the nodes are in state `NotReady` and tainted (`node.kubernetes.io/unreachable:NoSchedule`) by design.

We would like to ignore those nodes for the purposes of cluster proportional autoscaling.

Does this sound like a feature worthwhile of adding? I might be considering to contribute an implementation, although I'm not familiar with the codebase yet, as I think this might be quite easy to implement considering labels are already filtered.

My proposal would be to add a new option (e.g. `--nodetaints` analogous to `--nodelabels`) that would exclude nodes based on specified taints.

**Comment by MrHohn** [comment]
Hi @tbalzer, thanks for the use case. That sounds like a reasonable feature and a new option like you proposed makes sense. Would appreciate it if anyone could send a PR :)
