### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by nathanperkins** [kubernetes-sigs/cluster-proportional-autoscaler#118]
I noticed that a lot of the packages in the go.mod are using versions from 2-4 years ago and are probably worth an update at this point.

I made a pass at using `go get -u` and `go mod tidy` to upgrade them, but there were a number of conflicts arising from packages changing names and/or repositories.

**Comment by kundan2707** [comment]
@MrHohn JUst wanted to check if you are working on it.
