### ISSUE TITLE
Released versions are not published

### ISSUE THREAD

**Issue by kuuji** [kubernetes-sigs/cluster-proportional-autoscaler#122]
After trying to pull k8s.gcr.io/cluster-proportional-autoscaler-amd64:1.8.5 and failing I noticed that the last 4 released haven't been published.

Couldn't find the pipeline that pushes that but I'm assuming it's broken currently.

**Comment by MrHohn** [comment]
@kuuji There were some changes for the vanity domain flip: https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/Vanity-Domain-Flip.md

The released images had been migrated to `k8s.gcr.io/cpa/cluster-proportional-autoscaler:X` instead. e.g. `k8s.gcr.io/cpa/cluster-proportional-autoscaler:1.8.5`.

You can find the available images on https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/1.8.5.

**Comment by kuuji** [comment]
Oh I see, thanks @MrHohn. I'll close this and point to the new location.
