### ISSUE TITLE
cluster-proportional-autoscaler-arm64:1.8.5 is not arm arch

### ISSUE THREAD

**Issue by tukwila** [kubernetes-sigs/cluster-proportional-autoscaler#123]
step1: pull docker image
docker pull k8s.gcr.io/cpa/cluster-proportional-autoscaler-arm64:1.8.5
step2: check image
$ docker images|grep autoscaler
k8s.gcr.io/cpa/cluster-proportional-autoscaler-arm64   1.8.5           1e25a96f93b4   11 months ago   39.3MB
step3: check image arch
$ docker inspect 1e25a96f93b4
[
    {
        "Id": "sha256:1e25a96f93b46bbb5b1054e9be33bac06d9f18c44766f1c55cc026a87363b3ef",
        "RepoTags": [
            "k8s.gcr.io/cpa/cluster-proportional-autoscaler-arm64:1.8.5"
        ],
        "RepoDigests": [
            "k8s.gcr.io/cpa/cluster-proportional-autoscaler-arm64@sha256:260ba0a774e8419e006f2a5fde05d2b7ec3da8dec59b5caad578813848c09e31"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2021-08-12T20:44:40.714355076Z",
        "Container": "2c0ef62f63c823079e59d3e7861ea3752ffa99cd9ccd03cf5105d311ef94060b",
        "ContainerConfig": {
            "Hostname": "2c0ef62f63c8",
            "Domainname": "",
            "User": "65532",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "ENTRYPOINT [\"/cluster-proportional-autoscaler\"]"
            ],
            "Image": "sha256:aa772d33416c148ada3fffbb8af0cc7a354fee67608135c61534da463afaf691",
            "Volumes": null,
            "WorkingDir": "/home/nonroot",
            "Entrypoint": [
                "/cluster-proportional-autoscaler"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "DockerVersion": "20.10.2",
        "Author": "Zihong Zheng <zihongz@google.com>",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "65532",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt"
            ],
            "Cmd": null,
            "Image": "sha256:aa772d33416c148ada3fffbb8af0cc7a354fee67608135c61534da463afaf691",
            "Volumes": null,
            "WorkingDir": "/home/nonroot",
            "Entrypoint": [
                "/cluster-proportional-autoscaler"
            ],
            "OnBuild": null,
            "Labels": null
        },
        **"Architecture": "amd64",**
        "Os": "linux",
        "Size": 39305878,
        "VirtualSize": 39305878,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/e302e10d9e0562baaac48b915430703bad258d50ad07d607726e75acb9ba3f3e/diff",
                "MergedDir": "/var/lib/docker/overlay2/ad7c5c5e5cddfe02378c3c77fd9a41b80bfeec0772325385360116eafb151679/merged",
                "UpperDir": "/var/lib/docker/overlay2/ad7c5c5e5cddfe02378c3c77fd9a41b80bfeec0772325385360116eafb151679/diff",
                "WorkDir": "/var/lib/docker/overlay2/ad7c5c5e5cddfe02378c3c77fd9a41b80bfeec0772325385360116eafb151679/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:07363fa8421000ad294c2881d17b0535aabdd17ced2a874eb354a9d8514d3d59",
                "sha256:07ff26a9ac179973db78bb37b0310269e5b096d14948f657b003aaa231dff786"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
the issue is: i want to pull cluster-proportional-autoscaler-arm64 image but the arch is amd64 that is different with its name.
so, please confirm this.

**Comment by MrHohn** [comment]
Thanks for the report - I suspect we will need a fix similar to https://github.com/kubernetes/dns/pull/529. If anyone is interested to take a stab that would be great!

**Comment by MrHohn** [comment]
Keeping @tstapler in the loop.

**Comment by MrHohn** [comment]
In fact, someone has attempted this https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/pull/117. I will pull that off for a quick local run.

**Comment by MrHohn** [comment]
I will cut a new 1.8.6 release for this: https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/1.8.6

**Comment by MrHohn** [comment]
https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/1.8.6 is out now.
