### ISSUE TITLE
The `appVersion` of the Helm Chart is not bumped up

### ISSUE THREAD

**Issue by tsub** [kubernetes-sigs/cluster-proportional-autoscaler#125]
Although [v1.8.5](https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/1.8.5) of the application has been released, the version that can be installed from the Helm chart is still v1.8.4.

https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/blob/d186f0a98ec77bdd4d34818588f13457777679d1/charts/cluster-proportional-autoscaler/Chart.yaml#L4

As a workaround, you can install any version by specifying `image.tag` in Helm Values, but it is not a good idea to let this situation persist.

https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/blob/d186f0a98ec77bdd4d34818588f13457777679d1/charts/cluster-proportional-autoscaler/values.yaml#L21-L24

It appears that the helm chart bump up is not part of the release cycle.

**Comment by kundan2707** [comment]
Updated  appVersion: 1.8.5

**Comment by tsub** [comment]
Thank you! However, it appears that [v1.8.6](https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/1.8.6) was released 7 days ago.

**Comment by kundan2707** [comment]
@tsub updated to 1.8.6

**Comment by tsub** [comment]
Looks like it was updated the `appVersion` with PR #127! Thank you very much.
