### ISSUE TITLE
Bump go version to resolve Golang CVEs 

### ISSUE THREAD

**Issue by MrHohn** [kubernetes-sigs/cluster-proportional-autoscaler#131]
/assign

**Comment by MrHohn** [comment]
Cut a new tag on https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/1.8.7.

**Comment by rtheis** [comment]
@MrHohn Thank you for this update. Do you have an estimate on when the `registry.k8s.io/cpa/cluster-proportional-autoscaler:1.8.7` image will be available?

**Comment by MrHohn** [comment]
Let's take the discussion to https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/issues/138.
