### ISSUE TITLE
info: 1.8.7 tag but no release

### ISSUE THREAD

**Issue by jtumber-ibm** [kubernetes-sigs/cluster-proportional-autoscaler#138]
Hi,

Wondering why there is a [1.8.7 tag](https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/1.8.7) but not a [release](https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases) to match. Specifically the 1.8.7 images haven't been published it seems. e.g. `k8s.gcr.io/cpa/cluster-proportional-autoscaler:1.8.7`

Thanks

**Comment by obohaciak** [comment]
Same question, but for tag [1.8.8](https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/v1.8.8)

**Comment by MrHohn** [comment]
Sorry for the delay folks. There has been a few issue on the image release flow that finally got resolved now. https://github.com/kubernetes/k8s.io/pull/5086 is promoting the v1.8.8 image and I will tag a release after that is merged.

Regarding 1.8.7 - it appears to contains undesirable golang CVEs and we decided to skip it. v1.8.8 should be the latest good version to consume.

**Comment by obohaciak** [comment]
Thank you @MrHohn, much appreciated! 1.8.8 is exactly what we need, we've been anxiously waiting for a patch for the golang CVE.

**Comment by huoqifeng** [comment]
> Sorry for the delay folks. There has been a few issue on the image release flow that finally got resolved now. [kubernetes/k8s.io#5086](https://github.com/kubernetes/k8s.io/pull/5086) is promoting the v1.8.8 image and I will tag a release after that is merged.
> 
> Regarding 1.8.7 - it appears to contains undesirable golang CVEs and we decided to skip it. v1.8.8 should be the latest good version to consume.

thanks @MrHohn , does the new v1.8.8 release also include s390x? It was included releases ealier than v1.8.6 but seems missed from v1.8.6

**Comment by MrHohn** [comment]
Not sure what happened on 1.8.6 but yes v1.8.8 should include s390x  - here is the manifest from staging (`gcr.io/k8s-staging-cpa/cluster-proportional-autoscaler:v1.8.8`):
```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2611,
         "digest": "sha256:93dc3d84636a5d7e45a44b1bef118f3181fded4c202fd183094df8daee1094a1",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2611,
         "digest": "sha256:492d97acbdcf281502b622f41c7d4deaa3a0955500131416acc85a3f334782f3",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2610,
         "digest": "sha256:d3d9f8ab5d3619fc1811bcff437d8a4f5739038fa02687275c843c1c107df8e5",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2610,
         "digest": "sha256:9fd3ab046c67b4069ab87e8395ee17da5c1a23118bfcf886649a25d732a23d07",
         "platform": {
            "architecture": "ppc64le",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2611,
         "digest": "sha256:e09691dc9070375498ea736a9637fea77571ff33883d50f9f0843c3bed0402e3",
         "platform": {
            "architecture": "s390x",
            "os": "linux"
         }
      }
   ]
}
```

**Comment by MrHohn** [comment]
v1.8.8 is released now: https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/v1.8.8
