### ISSUE TITLE
Deprecation of legacy k8s.gcr.io container image registry

### ISSUE THREAD

**Issue by maciejogrodniczek-identt** [kubernetes-sigs/cluster-proportional-autoscaler#140]
As the current registry that is serving the image is going to freeze:
https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/
We have to migrate images to registry.k8s.io

Thanks.

**Comment by BenTheElder** [comment]
Note that all k8s.gcr.io images are already available at registry.k8s.io, you just need to update references to them and in the near future you'll publish them only to registry.k8s.io

**Comment by MrHohn** [comment]
We have published the latest release with reference to registry.k8s.io: https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/v1.8.8-rc.1

The only thing left is to update the existing references to the old registry, primarily manifests under https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/tree/master/examples. I'm looking for a volunteer for that :)

**Comment by kundan2707** [comment]
@MrHohn  i would like to update those references.
