### ISSUE TITLE
Request for Inclusion of Compatibility Matrix in README.md

### ISSUE THREAD

**Issue by kirtanc25** [kubernetes-sigs/cluster-proportional-autoscaler#145]
**Issue Description:**
I would like to request the inclusion of a compatibility matrix in the README.md file of the `cluster-proportional-autoscaler` repository. The compatibility matrix would provide users with a clear overview of the Kubernetes versions supported by the tool.

A compatibility matrix is essential for users to quickly determine whether the `cluster-proportional-autoscaler` is compatible with their specific Kubernetes version, thus ensuring a smooth integration and usage experience.

An excellent example of a compatibility matrix can be found in the `metrics-server` repository's README.md file, specifically at this location: https://github.com/kubernetes-sigs/metrics-server#compatibility-matrix. This matrix serves as a useful reference for users to understand the supported Kubernetes versions by the metrics-server tool.

<img width="660" alt="image" src="https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/assets/41354607/d7ee4685-2767-4d74-8205-74cce33a4657">

By including a compatibility matrix in the README.md file of the `cluster-proportional-autoscaler` repository, users would greatly benefit from the clear and concise information regarding the supported Kubernetes versions.

Thank you for considering this feature request. Please let me know if any additional information is required.

**Comment by vadasambar** [comment]
Had question around compatibility as well. Looking at the latest commit at the time of writing this comment: https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/commit/a24cff63b0d93bf627c607bc0fe6ead68e15ce28 

The code seems to have direct dependency on 
https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/blob/a24cff63b0d93bf627c607bc0fe6ead68e15ce28/go.mod#L9-L13

>  A v0 version does not make any stability guarantees, so nearly all projects should start with v0 as they refine their public API.

https://go.dev/blog/publishing-go-modules

That being said, 

### k8s.io/api v0.26.3
> Branches track Kubernetes branches and are compatible with that repo.

https://github.com/kubernetes/api/tree/v0.26.3#compatibility

That is to say, 

<img width="410" alt="image" src="https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/assets/34534103/0701b49d-ec33-4602-a70a-b03276423981">

it supports Kubernetes v1.26 version. 

This is the last commit on v0.26.3 at the time of writing this comment. 
https://github.com/kubernetes/api/commit/699cbbc336e23257e05cd1e5c97343e64ec4ccb3

### k8s.io/apimachinery v0.26.3 

> There are NO compatibility guarantees for this repository. It is in direct support of Kubernetes, so branches will track Kubernetes and be compatible with that repo. As we more cleanly separate the layers, we will review the compatibility guarantee.

https://github.com/kubernetes/apimachinery/tree/v0.26.3

<img width="540" alt="image" src="https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/assets/34534103/1adc0b38-a6d4-490c-8291-5ba3a8d51eb5">

https://github.com/kubernetes/apimachinery/commit/53ecdf01b997ca93c7db7615dfe7b27ad8391983

### k8s.io/client-go v0.26.3 

> For each v1.x.y Kubernetes release, the major version (first digit) would remain 0.

https://github.com/kubernetes/client-go/tree/v0.26.3#versioning

Basically, v1.26 version of Kubernetes

<img width="410" alt="image" src="https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/assets/34534103/b793ac3b-7fe6-4378-abc9-f3a91b6bae18">

https://github.com/kubernetes/client-go/commit/8cbca742aebe24b24f7f4e32fd999942fa9133e8

### k8s.io/component-base v0.26.3 
> There are NO compatibility guarantees for this repository, yet. It is in direct support of Kubernetes, so branches will track Kubernetes and be compatible with that repo. As we more cleanly separate the layers, we will review the compatibility guarantee. We have a goal to make this easier to use in the future.

https://github.com/kubernetes/component-base/tree/v0.26.3

<img width="418" alt="image" src="https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/assets/34534103/1b9533c5-f1d4-4037-a453-d58963250f24">

https://github.com/kubernetes/component-base/commit/1056e8d0d5a644c29c9a0aafbc472d053645fba3

### k8s.io/utils v0.0.0-20230313181309-38a27ef9d749 
No releases (or tags yet). 
<img width="1311" alt="image" src="https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/assets/34534103/e48179e8-dd01-4153-98e1-b033dc711ffa">


As a basic rule of thumb, it seems like when the go.mod `k8s.io` import point to version `v0.X.Y`, it supports a Kuberentes version `1.X`. e.g., if the library version is `v0.26.3`, it supports Kubernetes version `v1.26`
