### ISSUE TITLE
tag for 1.8.8 includes v

### ISSUE THREAD

**Issue by flerchin** [kubernetes-sigs/cluster-proportional-autoscaler#146]
For consistency, I'd like all the tags to be formatted the same. Are we expecting to use `v.A.C.D` going forward? All previous tags are `A.B.C`

**Comment by MrHohn** [comment]
Hi @flerchin, thanks for asking. Yes, I would +1 on the consistency and we are expecting to use `v.A.C.D` going forward. This move is also for consistency with the other repos within kubernetes-sigs (e.g. https://github.com/kubernetes-sigs/cluster-proportional-vertical-autoscaler/tags) as well [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/tags).

**Comment by MrHohn** [comment]
I released this is not well documented so I update https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/v1.8.8 to call this out.
