### ISSUE TITLE
Missing 1.8.10 release

### ISSUE THREAD

**Issue by davidbartos** [kubernetes-sigs/cluster-proportional-autoscaler#186]
Hi folks,

I happened to come across that, although a `1.8.10` tag is available, the corresponding release and the image is unavailable/missing. Is there any particular reason these are not published yet? Do you plan to release the `1.8.10` in the near future?

**Comment by rtheis** [comment]
1.8.11 is missing too:

```
root@verify-cluster:~# docker pull registry.k8s.io/cpa/cluster-proportional-autoscaler:v1.8.10
Error response from daemon: manifest for registry.k8s.io/cpa/cluster-proportional-autoscaler:v1.8.10 not found: manifest unknown: Failed to fetch "v1.8.10"
root@verify-cluster:~# docker pull registry.k8s.io/cpa/cluster-proportional-autoscaler:v1.8.11
Error response from daemon: manifest for registry.k8s.io/cpa/cluster-proportional-autoscaler:v1.8.11 not found: manifest unknown: Failed to fetch "v1.8.11"
root@verify-cluster:~# 
```

**Comment by MrHohn** [comment]
Hey folks, sorry for the delay on responding. We are cutting a new release on https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/issues/215 for 1.9.0 now.
