### ISSUE TITLE
Any way to disable when node(s) are being shutdown?

### ISSUE THREAD

**Issue by boatmisser** [kubernetes-sigs/cluster-proportional-autoscaler#209]
Just a Question, sorry about using Issue.

I was trying to use proportional autoscaler to replicate a Daemonset using a Deployment by having 1 pod per node.

However, during a cluster scaler up (for a large app deployment) and then back down; the proportional autoscaler prevented the removal of nodes, resulting in an ever-larger cluster.

I was just wondering if it's possible to configure so that it does not prevent a node scale down during a cluster autoscale re-balance. E.g. 20 node cluster; deployment causes 4 new nodes; these get a pod due to proportional autoscaler; cluster autoscaler then tries to remove 4 nodes afgter re-balance and can't.

Thanks

**Comment by kundan2707** [comment]
When pods are evicted during the graceful node shutdown, they are marked as shutdown. Running kubectl get pods shows the status of the evicted pods as Terminated. HPA still considers these pods to be a healthy part of the deployment and will not scale up or down to fulfill the desired state based on the metrics. so there is no need of disabling

**Comment by kundan2707** [comment]
@boatmisser was you able to achieve this ?
