### ISSUE TITLE
Estimated timeline for a new release with security fixes 

### ISSUE THREAD

**Issue by SriHarsha001** [kubernetes-sigs/cluster-proportional-autoscaler#215]
Do we have any estimated timeline for a new release that contains the latest security fixes ?

**Comment by MrHohn** [comment]
Let me take sweep and pick up what is needed for the next release. ETA this month.
/assign

**Comment by MrHohn** [comment]
Tag [v1.9.0](https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/v1.9.0) had been cut. Staging images are being promoted on https://github.com/kubernetes/k8s.io/pull/7525. Once that's done, we will publish a new release.

**Comment by MrHohn** [comment]
https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/v1.9.0 - release has been published.
