### ISSUE TITLE
Unbalanced number of replicas per node

### ISSUE THREAD

**Issue by srspnda** [kubernetes-sigs/cluster-proportional-autoscaler#80]
Hi there. I'm seeing behavior with this autoscaler that doesn't align with my expectation. My expectation is that with `linear` mode, `coresPerReplica: 1`, a 6 node cluster with 8 cores per node would then see 8 replicas on each node, for a total of 48. This would provide an evenly distributed CPU request buffer across the cluster, where each node would have ~20% of its allocated CPU requests filled with "pause" pods.

However, when deploying the autoscaler it seems that I am seeing an uneven distribution, and different results each time with respect to distribution. I am seeing 48 replicas in total but the distribution is not what I expected. In particular I'm seeing that it is consistently not putting replicas (or very little) on a node with about 48% of cpu requests/limits allocated. But with a 200m pause pod replica, and 1 core per replica there is plenty of space for the overprovisioning autoscaler to allocate 200m * 8 replicas on this node.

Let me know what additional information you would like, if any. Thanks!

**Comment by srspnda** [comment]
After reading the code I see that the autoscaler is just updating the replica count of the target object from math done on values retrieved by polling the API server. So I can't expect exactly even distribution.

Though, I have noticed that after updating the autoscaler image or doing a worker node update that fairly uneven distribution can occur. Are there ways that others are handling this issue other than redeploying everything?

**Comment by MrHohn** [comment]
@srspnda Great observation, as you analyzed, CPA doesn't do anything regarding the scheduling part, it merely updates the replica field to what is expected.

To tune the scheduling behavior, you probably want to utilize scheduler related features, such as `Pod Topology Spread Constraints` [1] or `Affinity and anti-affinity` [2].

[1] https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
[2]https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity

**Comment by srspnda** [comment]
Thank you for the response. I enjoyed reading about the `Pod Topology Spread Constraints` as that feels more in alignment with addressing the issue. Unfortunately clusters I'm operating on are in Amazon EKS, and the latest is v1.15.

My concern with using `anti-affinity` is based on the fact I don't understand what impact that could have on the cluster-autoscaler.

**Comment by MrHohn** [comment]
> My concern with using anti-affinity is based on the fact I don't understand what impact that could have on the cluster-autoscaler.

I don't see much conflict using that with the autoscaler together. In fact, we did that some times back by enabling anti-affinity on kube-dns (which has this autoscaler enabled) to spread out the pod distribution. Unfortunately that was [rolled back](https://github.com/kubernetes/kubernetes/pull/59357) for other reasons ([performance issue](https://github.com/kubernetes/kubernetes/issues/54164) for the anti-affinity feature on large cluster).
