### ISSUE TITLE
Operating from outside a cluster

### ISSUE THREAD

**Issue by ereslibre** [kubernetes-sigs/cluster-proportional-autoscaler#83]
I was wondering if it would be welcome a new feature that will allow users to run the `cluster-proportional-autoscaler` outside of the cluster that is autoscaling.

The use case is as follows:

* Given a managed Kubernetes service, I want the cluster proportional autoscaler to automatically scale my CoreDNS deployment based on the number of nodes/load.

In this case, the cluster consumer will get benefit from the autoscaling logic, but will not see the cluster-proportional-autoscaler, since this component will be running from outside the cluster (provided with a kubeconfig file through a new `--config` or `--kubeconfig` argument).

If this argument is not provided, the `cluster-proportional-autoscaler` will fallback to the in-cluster regular operation.

Please let me know, if there's interest I can provide a PR.

**Comment by MrHohn** [comment]
@ereslibre Thanks for asking. I don't see why not, please feel free to send a PR. Thanks.

**Comment by ereslibre** [comment]
Thank you @MrHohn, will prepare one as soon as I can!
