### ISSUE TITLE
Unable to compute integer values of schedulable cores in the cluster.

### ISSUE THREAD

**Issue by loxo33** [kubernetes-sigs/cluster-proportional-autoscaler#86]
Found on Kubernetes 1.13 and 1.14 servers; upgrading Autoscaler from 1.7.1 to 1.8.0.

The autoscaler errors with:
```
"1 autoscaler_server.go:108] Error while getting cluster status: unable to compute integer values of schedulable cores in the cluster"
```
It looks like the change in `autoscaler_server.go` didn't account for the return value being a string instead of an integer:

```
kubectl get node ip-some-node.foo.bar -o json | jq .status.capacity.cpu
"8"

kubectl get node ip-some-node.foo.bar -o json | jq .status.allocatable.cpu
"7910m"
```

**Comment by lemonli** [comment]
my falt

**Comment by MrHohn** [comment]
Will publish v1.8.1 to pick up the fix.

**Comment by MrHohn** [comment]
1.8.1 release has been published.

**Comment by dudicoco** [comment]
@MrHohn can you please add a note to the 1.8.0 release that it has a bug and 1.8.1 should be used instead? I've just installed 1.8.0 and encountered this error

**Comment by MrHohn** [comment]
@dudicoco Sorry for the trouble. Just updated the 1.8.0 release note to mention this.

**Comment by dudicoco** [comment]
Thanks @MrHohn :)
