### ISSUE TITLE
Publish multi-arch image manifest

### ISSUE THREAD

**Issue by rifelpet** [kubernetes-sigs/cluster-proportional-autoscaler#89]
We're working on adding ARM64 support in Kops but in order to do that we need to use multi-architecture images for all of our addons because the nodes they could be scheduled on could span multiple architectures. Currently the CPA releases have separate images per architecture but it would be great to have a single image manifest for all architectures.

Adding support for this could be as simple as adding these [docker manifest commands](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/) to the Makefile. Any objection to supporting this? We can provide assistance if needed.

**Comment by MrHohn** [comment]
https://github.com/kubernetes/k8s.io/pull/1096 is promoting the 1.8.2 staging images to prod.

**Comment by MrHohn** [comment]
CPA 1.8.2 has been released: https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/1.8.2

And a multi-arch image is available on k8s.gcr.io/cpa/cluster-proportional-autoscaler:1.8.2

**Comment by hakman** [comment]
Thanks @MrHohn :)

**Comment by hakman** [comment]
@MrHohn I think something went wrong with the multi-arch image pushing. Could you check?
```bash
$ docker pull k8s.gcr.io/cpa/cluster-proportional-autoscaler:1.8.2 --platform arm64
1.8.2: Pulling from cpa/cluster-proportional-autoscaler
no matching manifest for linux/arm64 in the manifest list entries
```

**Comment by MrHohn** [comment]
Yep looks like the multi-arch image is wrong:
```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 945,
         "digest": "sha256:e310b7e60ed5dabcf9945fb86ee049bafde69b01ac0b9eb647c2b96c273e18d8",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 945,
         "digest": "sha256:ba9d51870f9a718f91fb2a0df6366da36b2e5484a3331049b226310b5d59993d",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 945,
         "digest": "sha256:549b40bf6c29920f0f023fd97a6a9197f785f15799523c3486456a1bd24c840f",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 945,
         "digest": "sha256:a9ba5e939a4f8f0ded4a6b222d01b6922fce231f7977098112d51e409fce81f0",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      }
   ]
}
```

**Comment by MrHohn** [comment]
Can't tell how the push command is wrong though (local run against my own gcr repo):
```
docker manifest create gcr.io/zihongz-k8s-dev/cluster-proportional-autoscaler:1.8.2 \
  --amend gcr.io/zihongz-k8s-dev/cluster-proportional-autoscaler-amd64:1.8.2 \
  --amend gcr.io/zihongz-k8s-dev/cluster-proportional-autoscaler-arm:1.8.2 \
  --amend gcr.io/zihongz-k8s-dev/cluster-proportional-autoscaler-arm64:1.8.2 \
  --amend gcr.io/zihongz-k8s-dev/cluster-proportional-autoscaler-ppc64le:1.8.2
```

johngmyers@ Any idea?

**Comment by MrHohn** [comment]
Humm looks like cross-build image will be labeled with a wrong architecture.. https://github.com/moby/moby/issues/35158

We can probably edit the architecture afterward via `docker manifest annotate`,  for instance:
https://github.com/kubernetes/dns/blob/4e5fdbaa4659e2d4c28b880c9212077ba1cd313e/rules.mk#L78-L85

**Comment by johngmyers** [comment]
Yeah, I can't figure out a way to correct the arch metadata for the single-arch images. Filed #94.

**Comment by MrHohn** [comment]
https://github.com/kubernetes/k8s.io/pull/1131 is promoting the new images that include the fix.

**Comment by MrHohn** [comment]
1.8.3 is out: https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/1.8.3

Hope that fixes the issue!

**Comment by hakman** [comment]
Thanks for the help @MrHohn. It works perfectly:
https://testgrid.k8s.io/kops-misc#kops-aws-arm64-conformance
