### ISSUE TITLE
Update references to kubernetes-incubator

### ISSUE THREAD

**Issue by nikhita** [kubernetes-sigs/cluster-proportional-autoscaler#96]
The [kubernetes-incubator org](http://github.com/kubernetes-incubator) has been deprecated - https://github.com/kubernetes/community/issues/1922.

This repo still contains `kubernetes-incubator` in it's Makefile and import paths, so these should be updated.

**Comment by kundan2707** [comment]
@nikhita Can you please close this issue now?

**Comment by MrHohn** [comment]
Thanks @kundan2707!
