### ISSUE TITLE
cluster-proportional-autoscaler conflicts with HPA CPU

### ISSUE THREAD

**Issue by shaharr-ma** [kubernetes-sigs/cluster-proportional-autoscaler#99]
While using cluster-proportional-autoscaler for CoreDNS scaling - https://gist.github.com/MrHohn/1198bccc2adbd8cf3b066ab37ccd8355#enable-dns-horizontal-autoscaling-feature it seems like CPA gets conflicts with CoreDNS HPA (cpu based). 

I.E: 
CPA scale up from 3 to 4: Replicas are not as expected : updating replicas from 3 to 4
But CoreDNS CPU HPA immediately scale-down from 4 to 3:  Normal  SuccessfulRescale  3m21s (x158 over 40d)  horizontal-pod-autoscaler  New size: 3; reason: All metrics below target

How should i manage this issue ?

**Comment by MrHohn** [comment]
@shaharr-ma I wouldn't expect this to work if you already enabled HPA on CoreDNS. Essentially you are using two autoscaling mechanisms that based on different attributes. My recommendation would be turning off one of them depends on your use case.
